@startuml createProjectUC
left header
<font color=000 size=18><b>Package:</b> UCD_1

<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Створення проекту
<font color=000 size=16><b>Учасники:</b> Менеджер, Система
<font color=000 size=16><b>Передумови:</b> План проекту не створений
<font color=000 size=16><b>Результат:</b> План проекту створений
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні

<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Менеджер|
start
:Пише концепцію проекту;

|Система|
:Інтерпретує подання;
:Показує план схематично;

|Менеджер|
:Підтверджує;

|Система|
:Зберігає план в базу даних;

|Менеджер|
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml
