@startuml handleResult
left header
<font color=000 size=18><b>Package:</b> UCD_1

<font color=000 size=16><b>ID:</b> UC_5
<font color=000 size=16><b>Назва:</b> Виконання задачі
<font color=000 size=16><b>Учасники:</b> Менеджер проекту, Система
<font color=000 size=16><b>Передумови:</b> Виконання задачі
<font color=000 size=16><b>Результат:</b> Перевірка виконання пройдена
<font color=000 size=16><b>Виключні ситуації:</b> EX_1 Обробка помилок

<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Система|
start
:Надсилає повідомлення тестувальнику;

|Тестувальник|
:Підтверджує отримання;
:Перевіряє якість виконання;
:Передає дані про якість
виконання в систему;
note right #aaffaa
<font color=red><b>Може ініціювати EX_1
<font color=red><b>ситуацію "Обробка помилок"
end note

|Система|
:Збергає дані про якість
виконання в базу даних;
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml
