@startuml handleResultUC

left header
<font size=16 color=black><b>Перевірка виконання:</b> 
end header

|Система|
start
:Надсилає повідомлення тестувальнику;

|Тестувальник|
:Підтверджує отримання;
:Перевіряє якість виконання;
:Передає дані про якість
виконанання в систему;
note right #aaffaa
<font color=red><b>Може ініціювати
<font color=red><b>ситуацію "Обробка помилок"
end note

|Система|
:Збергає дані про якість
виконання в базу даних;
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml