@startuml handleErrorsUC
left header
<font color=000 size=18><b>Package:</b> UCD_1

<font color=000 size=16><b>ID:</b> UC_7
<font color=000 size=16><b>Назва:</b> Обробка помилок
<font color=000 size=16><b>Учасники:</b> Тестувальник, Система, Менеджер
<font color=000 size=16><b>Передумови:</b> Приходять помилки
<font color=000 size=16><b>Результат:</b> Помилки виправлено
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні

<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Тестувальник|
start
:Ініціює процедуру;
note right #aaffaa
Може додати свій сценарій її вирішення
end note

|Система|
:Оновлює стан задачі;
:Надсилає повідомлення менеджеру;

|Менеджер|
:Отримує повідомлення;
:Формує сценарій вирішення проблеми;
:Підтверджує;

|Система|
:Оновлює стан задачі;
:Розсилає повідомлення 
про нові задачі за сценарієм;

|Тестувальник|
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml
