@startuml handleErrorsUC

left header
<font size=16 color=black><b>Обробка помилок:</b> 
end header

|Тестувальник|
start
:Ініціює процедуру;
note right #aaffaa
Може додати свій сценарій її вирішення
end note

|Система|
:Оновлює стан задачі;
:Надсилає повідомлення менеджеру;

|Менеджер|
:Отримує повідомлення;
:Формує сценарій вирішення проблеми;
:Підтверджує;

|Система|
:Оновлює стан задачі;
:Розсилає повідомлення 
про нові задачі за сценарієм;

|Тестувальник|
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml