@startuml resolveTask
left header
<font color=000 size=18><b>Package:</b> UCD_1

<font color=000 size=16><b>ID:</b> UC_5
<font color=000 size=16><b>Назва:</b> Передача результату роботи
<font color=000 size=16><b>Учасники:</b> Менеджер проекту, Система
<font color=000 size=16><b>Передумови:</b> Виконана задача робітником
<font color=000 size=16><b>Результат:</b> Подальша перевірка
<font color=000 size=16><b>Виключні ситуації:</b> Відсутні

<font color=000 size=16><b>Основний сценарій:</b> 

end header

|Робітник|
start
:Вносить в систему результат роботи;

|Система|
:Підтверджує отримання;
:Оновлює стан задачі;
:Надсилає повідомлення
відповідальному тестувальнику;

|Робітник|
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml
