@startuml resolveTaskUC

left header
<font size=16 color=black><b>Передача результату:</b> 
end header

|Робітник|
start
:Вносить в систему результат роботи;

|Система|
:Підтверджує отримання;
:Оновлює стан задачі;
:Надсилає повідомлення
відповідальному тестувальнику;

|Робітник|
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml