@startuml runProjectUC

left header
<font size=16 color=black><b>Запуск проекту:</b> 
end header

|Менеджер|
start
:Обирає сценарій зі списку;

|Система|
:Інтерпретує сценарій;
:Показує сценарій схематично;

|Менеджер|
:Вносить адаптаційні правки;
:Підтверджує;

|Система|
:Генерує завдання і зберігає їх в базу даних;

|Менеджер|
stop

right footer
НТУУ КПІ ім.І.Сікорського
Киів, 2020 
end footer
@enduml